[project]
name = "chatstorage"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.5",
    "cachetools>=7.1.1",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "fastmcp>=3.2.4",
    "loguru>=0.7.3",
    "pymongo>=4.17.0",
    "python-jose[cryptography]>=3.5.0",
    "starlette>=1.0.0",
    "tenacity>=9.1.4",
    "uvicorn>=0.46.0",
    "dotenv>=0.9.9",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
